spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/orders
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  liquibase:
    enabled: true

open-api:
  server-url: http://localhost:8080


application:
  default-order-items-page-number: 0
  default-order-items-page-size: 10
  default-order-sort-value: customerName